version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: "dipuvish5/solution-architecture:latest"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://deepak:deepak@cluster-0.leprs.mongodb.net/?retryWrites=true&w=majority&appName=Cluster-0
      - NODE_ENV=production
    ports:
      - "80:80"
    restart: always
