version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      platform: linux/arm64  # Specify ARM64 platform for EC2
    image: "${DOCKER_USERNAME}/solution-architecture:latest"  # Replace with your Docker Hub username and repo name
    environment:
      SPRING_DATA_MONGODB_URI: mongodb+srv://deepak:deepak@cluster-0.leprs.mongodb.net/?retryWrites=true&w=majority&appName=Cluster-0
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: always
